# Generated by Django 3.2.12 on 2022-03-31 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestTable',
            fields=[
                ('first_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
            ],
            options={
                'db_table': 'testtable',
            },
        ),
        migrations.CreateModel(
            name='UniDetails',
            fields=[
                ('uniqueid', models.IntegerField(primary_key=True, serialize=False)),
                ('logo', models.CharField(max_length=30)),
                ('link', models.CharField(max_length=30)),
                ('research_output', models.CharField(max_length=30)),
                ('student_faculty_ratio', models.FloatField()),
                ('international_students', models.IntegerField()),
                ('size', models.CharField(max_length=30)),
                ('faculty_count', models.IntegerField()),
            ],
            options={
                'db_table': 'unidetails',
            },
        ),
        migrations.CreateModel(
            name='UniversityList',
            fields=[
                ('uniqueid', models.IntegerField(primary_key=True, serialize=False)),
                ('university', models.CharField(max_length=30)),
                ('year', models.IntegerField()),
                ('rank_display', models.IntegerField()),
                ('score', models.FloatField()),
                ('country', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'universitylist',
            },
        ),
    ]
